version: '3.1'

services:
  springboot:
    image: krishnapuppala97/spring_boot:latest
    restart: always # This will be ignored if we deploy in docker swarm
    ports:
      - 8081:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    networks:
    - springappnetwork

  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
    restart: always
    networks:
    - springappnetwork

volumes:
  mongodb:

networks:
  springappnetwork:
